version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "22:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: webpack-cli
    versions:
    - 4.3.1
    - 4.4.0
    - 4.5.0
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.2
    - 11.2.3
    - 11.2.5
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.2.2
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.3
    - 1.3.5
    - 1.3.9
  - dependency-name: html-webpack-plugin
    versions:
    - 4.5.0
    - 4.5.1
  - dependency-name: react-intl
    versions:
    - 5.10.10
    - 5.11.0
  - dependency-name: ts-loader
    versions:
    - 8.0.13
    - 8.0.14
  - dependency-name: "@types/jest"
    versions:
    - 26.0.19
    - 26.0.20
  - dependency-name: webpack-dev-server
    versions:
    - 3.11.1
  - dependency-name: dotenv-webpack
    versions:
    - 6.0.0
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.0
  - dependency-name: "@types/react"
    versions:
    - 17.0.0
  - dependency-name: css-loader
    versions:
    - 5.0.1
  - dependency-name: "@types/react-loadable"
    versions:
    - 5.5.4
  - dependency-name: webpack
    versions:
    - 4.44.2
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
